### PR TITLE
Products: adds `page` function

### PR DESCRIPTION
**Pull request by samm81**
also adds associations between `User` & `Product` and `User` & `Seller`

in preparation for the main shop page, but this can be reviewed & merged already

I went through the whole flow (creating a user account, creating a new product, editing my seller account page) and everything seemed ok, so seems like these associations get added "for free" which is nice

can see in the below `iex` session that `Products.page/2` now correctly preloads `[user: [:seller]]` for free, so no need to do manual joins in the code anymore

```
iex(4)> Products.page(1)
[debug] QUERY OK source="products" db=1.0ms idle=1401.8ms
SELECT p0."id", p0."user_id", p0."product_type", p0."name", p0."price", p0."internal_expense", p0."description", p0."designs", p0."mocks", p0."campaign_duration", p0."campaign_duration_timestamp", p0."active", p0."curated", p0."top", p0."inserted_at", p0."updated_at" FROM "products" AS p0 WHERE (p0."active" = TRUE) ORDER BY p0."inserted_at" DESC, p0."id" DESC LIMIT $1 [2]
↳ Paginator.paginate/4, at: lib/paginator.ex:179
[debug] QUERY OK source="users" db=1.9ms idle=1403.4ms
SELECT u0."id", u0."email", u0."hashed_password", u0."confirmed_at", u0."inserted_at", u0."updated_at", u0."id" FROM "users" AS u0 WHERE (u0."id" = ANY($1)) [[5, 6]]
↳ Paginator.paginate/4, at: lib/paginator.ex:179
[debug] QUERY OK source="sellers" db=1.2ms idle=405.8ms
SELECT s0."id", s0."user_id", s0."store_name", s0."store_handle", s0."profile_photo_url", s0."description", s0."location", s0."website", s0."socials", s0."stripe_id", s0."inserted_at", s0."updated_at", s0."user_id" FROM "sellers" AS s0 WHERE (s0."user_id" = ANY($1)) [[5, 6]]
↳ Paginator.paginate/4, at: lib/paginator.ex:179
%Paginator.Page{
  metadata: %Paginator.Page.Metadata{
    after: "g3QAAAACZAACaWRhEGQAC2luc2VydGVkX2F0dAAAAAlkAApfX3N0cnVjdF9fZAAURWxpeGlyLk5haXZlRGF0ZVRpbWVkAAhjYWxlbmRhcmQAE0VsaXhpci5DYWxlbmRhci5JU09kAANkYXlhH2QABGhvdXJhCGQAC21pY3Jvc2Vjb25kaAJhAGEAZAAGbWludXRlYRtkAAVtb250aGEFZAAGc2Vjb25kYSFkAAR5ZWFyYgAAB-g=",
    before: nil,
    limit: 1,
    total_count: nil,
    total_count_cap_exceeded: nil
  },
  entries: [
    %Plaza.Products.Product{
      __meta__: #Ecto.Schema.Metadata<:loaded, "products">,
      id: 16,
      user_id: 6,
      user: #Plaza.Accounts.User<
        __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
        id: 6,
        email: "user-z@gmail.com",
        confirmed_at: nil,
        seller: %Plaza.Accounts.Seller{
          __meta__: #Ecto.Schema.Metadata<:loaded, "sellers">,
          id: 6,
          user_id: 6,
          user: #Ecto.Association.NotLoaded<association :user is not loaded>,
          store_name: "cat",
          store_handle: "cat",
          profile_photo_url: nil,
          description: "cat",
          location: "cat",
          website: "cat",
          socials: %Plaza.Accounts.Socials{
            instagram: nil,
            soundcloud: nil,
            twitter: nil
          },
          stripe_id: nil,
          inserted_at: ~N[2024-05-31 08:27:33],
          updated_at: ~N[2024-05-31 08:27:33]
        },
        products: #Ecto.Association.NotLoaded<association :products is not loaded>,
        inserted_at: ~N[2024-05-31 08:16:48],
        updated_at: ~N[2024-05-31 08:16:48],
        ...
      >,
      product_type: "camiseta-classic-white",
      name: "cat",
      price: 75.0,
      internal_expense: 66.9,
      description: "cat",
      designs: %Plaza.Products.Designs{
        front: "https://plaza-static-dev.s3.us-west-2.amazonaws.com/0147c7c9-812d-41cb-a180-807b99685847.png",
        back: nil,
        display: 0
      },
      mocks: %Plaza.Products.Mocks{
        front: "https://plaza-static-dev.s3.us-west-2.amazonaws.com/mock_0147c7c9-812d-41cb-a180-807b99685847.png",
        back: "https://plaza-static-dev.s3.us-west-2.amazonaws.com/mockups/mockup-back-white.png",
        front_zoom: "https://plaza-static-dev.s3.us-west-2.amazonaws.com/mock_zoom_0147c7c9-812d-41cb-a180-807b99685847.png",
        back_zoom: nil
      },
      campaign_duration: 7,
      campaign_duration_timestamp: ~N[2024-06-07 08:22:37],
      active: true,
      curated: false,
      top: false,
      inserted_at: ~N[2024-05-31 08:27:33],
      updated_at: ~N[2024-05-31 08:27:33]
    }
  ]
}
```

### CODE REVIEW

**Comment by mrmizz** [comment]
This is heat. Love the type definitions you're adding, too.

**Comment by mrmizz** [comment]
One concern that comes to mind is the scenario where we would want to fetch the `user` struct without having the `seller` struct and `product` array fetched with it. Can we configure queries to not fetch these associations when we *just* want the `user`?

**Comment by samm81** [comment]
> One concern that comes to mind is the scenario where we would want to fetch the `user` struct without having the `seller` struct and `product` array fetched with it. Can we configure queries to not fetch these associations when we _just_ want the `user`?

are you saying something like `Products.fetch_creator(product_id: non_new_integer())` ? I'm not sure why `Products.page` wouldn't fetch the `Product` array ...?

as for not fetching the `Seller`, sure that's easy, just remove `[:seller]` in `:preload` key. if such a need arises I'd probably rename this to `Products.page_user_seller_preloaded` and make a new fn `Products.page_user_preloaded`. what's the use case you're thinking of?

**Comment by mrmizz** [comment]
> > One concern that comes to mind is the scenario where we would want to fetch the `user` struct without having the `seller` struct and `product` array fetched with it. Can we configure queries to not fetch these associations when we _just_ want the `user`?
> 
> are you saying something like `Products.fetch_creator(product_id: non_new_integer())` ? I'm not sure why `Products.page` wouldn't fetch the `Product` array ...?
> 
> as for not fetching the `Seller`, sure that's easy, just remove `[:seller]` in `:preload` key. if such a need arises I'd probably rename this to `Products.page_user_seller_preloaded` and make a new fn `Products.page_user_preloaded`. what's the use case you're thinking of?

I missed / didn't notice the `preload` key. This all makes a ton of sense.
And I was referring to what the respective `User.page` function would look like. Would that query *always* fetch the seller and product associations. The answer is no, we'd need to pass the `preload` key(s). I've been and continue to be very impressed with Ecto (and Phoenix).

**Pull request merged**
